/**
 * This file was generated by the JPA Modeler
 */ 

package org.bird.db.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


@Entity
@Table(name="BIRD.AUTHOR")
public class Author implements Serializable { 

    @Column(name="ID",table="BIRD.AUTHOR",nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer id;

    @Column(name="LASTNAME",table="BIRD.AUTHOR",nullable=false)
    @Basic(optional=false)
    private String lastname;

    @Column(name="FIRSTNAME",table="BIRD.AUTHOR")
    @Basic
    private String firstname;

    @Column(name="BORN_LASTNAME",table="BIRD.AUTHOR")
    @Basic
    private String bornLastname;

    @Column(name="BORN_FIRSTNAME",table="BIRD.AUTHOR")
    @Basic
    private String bornFirstname;

    @Column(name="IMAGE",table="BIRD.AUTHOR",length=500)
    @Basic
    private String image;

    @Column(name="BIOGRAPHY",table="BIRD.AUTHOR")
    @Lob
    @Basic
    private String biography;

    @Column(name="COMMENT",table="BIRD.AUTHOR",length=500)
    @Basic
    private String comment;

    @Column(name="BORNDATE",table="BIRD.AUTHOR")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date borndate;

    @Column(name="CREATEDATE",table="BIRD.AUTHOR")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date createdate;

    @OneToMany(targetEntity = LinkAuthorCycle.class,mappedBy = "idAuthor")
    private List<LinkAuthorCycle> linkAuthorCycleCollection;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getBornLastname() {
        return this.bornLastname;
    }

    public void setBornLastname(String bornLastname) {
        this.bornLastname = bornLastname;
    }

    public String getBornFirstname() {
        return this.bornFirstname;
    }

    public void setBornFirstname(String bornFirstname) {
        this.bornFirstname = bornFirstname;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getBiography() {
        return this.biography;
    }

    public void setBiography(String biography) {
        this.biography = biography;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getBorndate() {
        return this.borndate;
    }

    public void setBorndate(Date borndate) {
        this.borndate = borndate;
    }

    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public List<LinkAuthorCycle> getLinkAuthorCycleCollection() {
        return this.linkAuthorCycleCollection;
    }

    public void setLinkAuthorCycleCollection(List<LinkAuthorCycle> linkAuthorCycleCollection) {
        this.linkAuthorCycleCollection = linkAuthorCycleCollection;
    }


}
