/**
 * This file was generated by the JPA Modeler
 */ 

package org.bird.db.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


@Entity
@Table(name="CYCLE")
public class Cycle implements Serializable { 

    @Column(name="ID",table="CYCLE",nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer id;

    @Column(name="TITLE",table="CYCLE",nullable=false,length=500)
    @Basic(optional=false)
    private String title;

    @Column(name="CYCLE",table="CYCLE")
    @Basic
    private Boolean cycle;

    @Column(name="NBRVOLUME",table="CYCLE",nullable=false)
    @Basic(optional=false)
    private short nbrvolume;

    @Column(name="COMMENT",table="CYCLE",length=500)
    @Basic
    private String comment;

    @Column(name="CREATIONDATE",table="CYCLE")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date creationdate;

    @ManyToOne(optional=false,targetEntity = Book.class)
    @JoinColumn(name="BOOK_ID",referencedColumnName="ID")
    private Book bookId;

    @OneToMany(targetEntity = LinkAuthorCycle.class,mappedBy = "idCycle")
    private List<LinkAuthorCycle> linkAuthorCycleCollection;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean isCycle() {
        return this.cycle;
    }

    public void setCycle(Boolean cycle) {
        this.cycle = cycle;
    }

    public short getNbrvolume() {
        return this.nbrvolume;
    }

    public void setNbrvolume(short nbrvolume) {
        this.nbrvolume = nbrvolume;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    public Book getBookId() {
        return this.bookId;
    }

    public void setBookId(Book bookId) {
        this.bookId = bookId;
    }

    public List<LinkAuthorCycle> getLinkAuthorCycleCollection() {
        return this.linkAuthorCycleCollection;
    }

    public void setLinkAuthorCycleCollection(List<LinkAuthorCycle> linkAuthorCycleCollection) {
        this.linkAuthorCycleCollection = linkAuthorCycleCollection;
    }


}
