/**
 * This file was generated by the JPA Modeler
 */ 

package org.bird.db.entity;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


@Entity
@Table(name="LINK_AUTHOR_CYCLE")
public class LinkAuthorCycle implements Serializable { 

    @Column(name="ID",table="LINK_AUTHOR_CYCLE",nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer id;

    @ManyToOne(optional=false,targetEntity = Author.class)
    @JoinColumn(name="ID_AUTHOR",referencedColumnName="ID")
    private Author idAuthor;

    @ManyToOne(optional=false,targetEntity = Cycle.class)
    @JoinColumn(name="ID_CYCLE",referencedColumnName="ID")
    private Cycle idCycle;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Author getIdAuthor() {
        return this.idAuthor;
    }

    public void setIdAuthor(Author idAuthor) {
        this.idAuthor = idAuthor;
    }

    public Cycle getIdCycle() {
        return this.idCycle;
    }

    public void setIdCycle(Cycle idCycle) {
        this.idCycle = idCycle;
    }


}
